apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-frontend
  namespace: guestbook
spec:
  replicas: 2
  selector:
    matchLabels:
      app: guestbook
  template:
    metadata:
      labels:
        app: guestbook
    spec:
      containers:
      - name: guestbook
        image: gcr.m.daocloud.io/google-samples/gb-frontend:v5
        ports:
        - containerPort: 80
        env:
        - name: REDIS_HOST
          value: "redis"
